require 'yaml' 
require_relative 'game'
require_relative 'computer_versus_computer_game'
require_relative 'person_versus_computer_game'
require_relative 'person_versus_person_game'
require_relative 'output_formatter'
require_relative 'node'
require_relative 'board_view'
require_relative 'player'
require_relative 'person_player'
require_relative 'computer_player'
require_relative 'nodemap'
require_relative 'game_config'

require_relative 'player_generator'
require_relative 'first_player_generator'
require_relative 'additional_player_generator'

require_relative 'input'
require_relative 'output'
require_relative 'message'
require_relative 'response'
require_relative 'user_interface'
require_relative 'board'
require_relative 'move_rater'